# fly.toml app configuration file generated for guessing-game on 2025-01-08T16:11:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guessing-game'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'npx sequelize-cli db:migrate --config src/config/db.cjs'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
